name: Backend - CI

on:
  pull_request:
    paths:
      - web/packages/backend/**
      - .github/workflows/backend-ci.yaml
  push:
    branches:
      - main
    paths:
      - web/packages/backend/**
      - .github/workflows/backend-ci.yaml

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./web/packages/backend
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out codes
        uses: actions/checkout@v4

      - name: Setup containers
        run: docker compose -f ../../../docker/docker-compose.yaml up -d

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - name: Lint
        run: bun check
      - name: Test
        run: bun test

      - name: Setup LCOV
        uses: hrishikesh-kadam/setup-lcov@v1
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v4
        with:
          coverage-files: "**/coverage/lcov.info"
          minimum-coverage: 70
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: "./web/packages/backend"
          update-comment: true
